In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import torch
a=torch.tensor([[13,36,39],[4,8,12]])
print("\n",a)
print(a.ndim)
print(a.shape)
print(a.numel)
print(a.dtype)
print(a.device)



 tensor([[13, 36, 39],
        [ 4,  8, 12]])
2
torch.Size([2, 3])
<built-in method numel of Tensor object at 0x7f321a8a96d0>
torch.int64
cpu


In [7]:
import torch
a=torch.ones([2,3],dtype=torch.int64)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [10]:
import torch
b=torch.rand(1,2)
print(b)
c=torch.randn(1,2)
print(c)

tensor([[0.8092, 0.6807]])
tensor([[-1.0858,  1.5730]])


In [20]:
import torch
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1])
print(a[2])
print(a[[1,2],1])
print(a[[1,2],1])
print(a[[0,1,2],2])



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor([7, 8, 9])
tensor([5, 8])
tensor([5, 8])
tensor([3, 6, 9])


In [26]:
import torch
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[2:3,0:3])#slicing



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[7, 8, 9]])


In [28]:
import torch
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b=torch.sum(a)
print(b)
print(a.sum())


tensor(45)
tensor(45)


In [48]:
import torch
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b=torch.tensor([[2,8,9],[5,6,8],[9,7,4]])
c=torch.add(a,b)
print(c)
d=torch.subtract(a,b)
print(d)
e=torch.multiply(a,b)
print(e)
f=torch.divide(a,b)
print(f)

tensor([[ 3, 10, 12],
        [ 9, 11, 14],
        [16, 15, 13]])
tensor([[-1, -6, -6],
        [-1, -1, -2],
        [-2,  1,  5]])
tensor([[ 2, 16, 27],
        [20, 30, 48],
        [63, 56, 36]])
tensor([[0.5000, 0.2500, 0.3333],
        [0.8000, 0.8333, 0.7500],
        [0.7778, 1.1429, 2.2500]])


In [46]:
import torch
a=torch.tensor([70,35,67,28,99])
print(a>50)
print(a[a>50])
print(a[a>34])
print(a[a<50])

tensor([ True, False,  True, False,  True])
tensor([70, 67, 99])
tensor([70, 35, 67, 99])
tensor([35, 28])
